# Numpy Tutorial

In [53]:
import numpy as np
import sys

In [3]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr.ndim

2

In [6]:
arr.size

9

In [7]:
type(arr)

numpy.ndarray

In [9]:
brr = np.array([1, 2, 3, 4])
brr

array([1, 2, 3, 4])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
a = np.ones((3, 3), dtype=np.int16)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [158]:
arr = np.empty([4, 4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr = np.linspace(0, 2, 9)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [47]:
arr = np.arange(8).reshape(2, 2, 2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a = np.arange(10000).reshape(100, 100)
np.set_printoptions(threshold=sys.maxsize) # changes the default limit of display 
a

, 7064, 7065,
        7066, 7067, 7068, 7069, 7070, 7071, 7072, 7073, 7074, 7075, 7076,
        7077, 7078, 7079, 7080, 7081, 7082, 7083, 7084, 7085, 7086, 7087,
        7088, 7089, 7090, 7091, 7092, 7093, 7094, 7095, 7096, 7097, 7098,
        7099],
       [7100, 7101, 7102, 7103, 7104, 7105, 7106, 7107, 7108, 7109, 7110,
        7111, 7112, 7113, 7114, 7115, 7116, 7117, 7118, 7119, 7120, 7121,
        7122, 7123, 7124, 7125, 7126, 7127, 7128, 7129, 7130, 7131, 7132,
        7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7142, 7143,
        7144, 7145, 7146, 7147, 7148, 7149, 7150, 7151, 7152, 7153, 7154,
        7155, 7156, 7157, 7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165,
        7166, 7167, 7168, 7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176,
        7177, 7178, 7179, 7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187,
        7188, 7189, 7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198,
        7199],
       [7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209, 

In [63]:
a = np.random.random(10)
print(a)
np.set_printoptions(precision=3)
print(a)

[0.283 0.359 0.807 0.107 0.416 0.874 0.143 0.469 0.165 0.13 ]
[0.283 0.359 0.807 0.107 0.416 0.874 0.143 0.469 0.165 0.13 ]


In [65]:
a = np.array([1.5e-10, 1.5, 1.6666])
print(a)
np.set_printoptions(suppress=True) # suppresses the use of scientific notation for small numbers
print(a)

[0.    1.5   1.667]
[0.    1.5   1.667]


In [67]:
a = np.arange(10)
sqr = a ** 2
sqr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [73]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)
print(a)
print(b)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [74]:
a * b   # elementwise product

array([[ 0,  5],
       [12, 21]])

In [75]:
a @ b   # matrix product

array([[ 6,  7],
       [26, 31]])

In [76]:
a.dot(b)    # matrix product

array([[ 6,  7],
       [26, 31]])

In [80]:
a = np.ones((2, 2), dtype=int)
b = np.random.random((2, 2))
# a *= b    b will not convert to int automatically
b *= a    a will convert to float
b

array([[0.537, 0.327],
       [0.544, 0.056]])

In [88]:
a = np.arange(9).reshape(3, 3)
print(a)
print("Sum: ", a.sum())
print("Min: ", a.min())
print("Max: ", a.max())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum:  36
Min:  0
Max:  8


In [91]:
print(a.min(axis=1))   # min of each row
print(a.sum(axis=1))   # sum of each row

[0 3 6]
[ 3 12 21]


In [93]:
print(a.cumsum())
print(a.cumsum(axis=1)) # col  

[ 0  1  3  6 10 15 21 28 36]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [103]:
a = np.arange(5) ** 2
print(a[0::2]) # start:end(not inclusive):step

[ 0  4 16]
1


In [108]:
a = np.arange(9).reshape(3, 3)
print(a[1, ...])    # a[1, :, :] or a[1]
for ele in a.flat:  # returns iterator of flat array
    print(ele)
a.ravel()   # returns flattened array

[3 4 5]
0
1
2
3
4
5
6
7
8


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
a.T # transposed array

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [116]:
a = np.arange(12).reshape(4, 3)
print(a)
a.reshape(3, 4) # doesn't change a itself
a.resize(3, 4)  # changes a
a

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a = np.arange(12).reshape(4, -1) # dimension give as -1 is calculated itself 
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
print("Horizontal Stack: \n", np.hstack((a, b)))
print("Vertical Stack: \n", np.vstack((a, b)))

Horizontal Stack: 
 [[0 1 0 1]
 [2 3 2 3]]
Vertical Stack: 
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [136]:
a = np.arange(9).reshape(3, 3)
print(np.hsplit(a, 3))
np.split(a, 3) # default split is vertical split

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [160]:
a = np.arange(10)
a[a>5]

array([6, 7, 8, 9])

In [186]:
def qsort(a):
    if len(a) > 1:
        pivot = a[0]
        less = a[a < pivot]
        equal = a[a == pivot]
        greater = a[a > pivot]
        return np.concatenate((qsort(less), equal, qsort(greater)))
    else:
        return a

a = np.array([5, 4, 3, 2, 1, 100], dtype=int)
qsort(a)

array([  1,   2,   3,   4,   5, 100])